trigger:
  branches:
    include:
      - main
      - rel/*

pr:
  branches:
    include:
      - main
      - rel/*

pool:
  vmImage: ubuntu-latest

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0d3cc2fe-71c4-459b-ae14-ac93ff043725'
  imageRepository: 'membership'
  containerRegistry: 'dotnetfoundation.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    version: 3.1.x

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  
- script: ./nbgv cloud
  displayName: Set Version


- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    buildContext: ./
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
